version: '3.8'

services:
  mypostgres:
    image: postgres:latest
    container_name: mypostgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./liquibase_schema.sql:/docker-entrypoint-initdb.d/liquibase_schema.sql
